FlaskWebProject1/FlaskWebProject1/__init__.py
"""
The flask application package.
"""
import os
from  . import db
from flask import Flask

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'FlaskWebProject1.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    db.init_app(app)

    #auth
    from . import views
    app.register_blueprint(views.bp)

    #blog
    from . import blog
    app.register_blueprint(blog.bp)
    app.add_url_rule('/', endpoint='index')

    return app

app= create_app()

import FlaskWebProject1.views

FlaskWebProject1/FlaskWebProject1/views.py
"""
Routes and views for the flask application.
"""
import json
import datetime
import pickle
import os
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

from datetime import datetime
from flask import render_template
from FlaskWebProject1.db import get_db
from FlaskWebProject1.db import init_db
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

SCOPES = ['https://www.googleapis.com/auth/calendar.events']

bp = Blueprint('auth', __name__)

#def connect_to():
#    creds = None

#    if os.path.exists('token.pickle'):
#        with open('token.pickle', 'rb') as token:
#            creds = pickle.load(token)

#    if not creds or not creds.valid:
#        if creds and creds.expired and creds.refresh_token:
#            creds.refresh(Request())
#        else:
#            flow = InstalledAppFlow.from_client_secrets_file(
#                'credentials.json', SCOPES)
#            creds = flow.run_local_server(port=0)

#        with open('token.pickle', 'wb') as token:
#            pickle.dump(creds, token)
    
#    service = build('calendar', 'v3', credentials=creds)  
#    return service

def connect_to():
    creds = None

    #if os.path.exists('token.pickle'):
    #    with open('token.pickle', 'rb') as token:
    #        creds = pickle.load(token)
    if session.get('cred'):
        creds = pickle.loads(session.get('cred'))

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)

        #with open('token.pickle', 'wb') as token:
        #    pickle.dump(creds, token)
            session['cred'] = pickle.dumps(creds)

    
    service = build('calendar', 'v3', credentials=creds)  
    return service

@bp.route('/contact')
def contact():
    """Renders the contact page."""
    return render_template(
        'contact.html',
        title='Contact',
        year=datetime.now().year,
        message='Your contact page.'
    )

@bp.route('/about')
def about():
    """Renders the about page."""
    return render_template(
        'about.html',
        title='About',
        year=datetime.now().year,
        message='Your application description page.'
    )

@bp.route('/login', methods=('GET', 'POST'))
def login():
    service = connect_to()
    if service:
      session['user']=True   
    return render_template('login.html')


@bp.route('/logout')
def logout():
    session['user']=False
    session['cred']=None
    if os.path.exists('token.pickle'):
        os.remove('token.pickle')
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if not session.get('user'):
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view


FlaskWebProject1/FlaskWebProject1/templates/about.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>This server was created by Vladislav Matveev</p>

{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/blog.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Events{% endblock %}</h1>
  {% if session.get('user') %}
<a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block li %}
  {% if session.get('user') %}
<li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
  {% endif %}
  {% if not session.get('user') %}
<li><a href="{{ url_for('auth.login') }}">Login</a></li>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
<article class="post">
    <header>
        <div>
            <h1>{{ post['summary'] }}</h1>
        </div>
    </header>
    <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
    <p class="start">Start:{{ post['start']['dateTime'][0:16] }}</p>
    <p class="end">End:{{ post['end']['dateTime'][0:16] }}</p>
    <p class="loc">{{ post['location'] }}</p>
</article>
    {% if not loop.last %}
<hr>
    {% endif %}
  {% endfor %}
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/contact.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Russia<br />
    Perm<br />
    <abbr title="Phone">P:</abbr>
    Only mail :)
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:vladislaw0159@gmail.com">vladislaw0159@gmail.com</a><br />
</address>

{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/create.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}


{% block content %}
<form method="post" style="display:flex; flex-direction:column">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="date">Date</label>
    <input type="date" name="date" id="date" value="{{ request.form['date'] }}" required>
    <label for="start">Start</label>
    <input name="start" id="start" value="{{ request.form['start'] }}" required>
    <label for="end">End</label>
    <input name="end" id="end" value="{{ request.form['end'] }}" required>
    <label for="loc">Location</label>
    <textarea name="loc" id="loc">{{ request.form['loc'] }}</textarea>
    <input type="submit" value="Save">
</form>
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/index.html
{% extends "layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Flask</h1>
    <p class="lead">Flask is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://flask.pocoo.org/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Flask gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://flask.pocoo.org/docs/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.python.org/pypi">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Flask Application</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/site.css" />
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript" src="https://student.psu.ru/etis/js/jquery.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
     window.jQuery || document.write('<script src="{{url_for('static', filename = 'jquery.js') }}">\x3C/script>')
    </script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Events Server</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('blog.index') }}">Home</a></li>
                    <li><a href="{{ url_for('auth.about') }}">About</a></li>
                    <li><a href="{{ url_for('auth.contact') }}">Contact</a></li>
                    {% if session.get('user') %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                    {% if not session.get('user') %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ year }} - Matveev Flask Application</p>
        </footer>
    </div>

    <script src="/static/scripts/jquery-1.10.2.js"></script>
    <script src="/static/scripts/bootstrap.js"></script>
    <script src="/static/scripts/respond.js"></script>
    {% block scripts %}{% endblock %}
    <!--<script src="/static/scripts/myajax.js"></script>-->
    
</body>
</html>

FlaskWebProject1/FlaskWebProject1/templates/login.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}



{% block content %}
  {% if not session.get('user') %}
<h1>Fail</h1>
  {% endif %}
  {% if session.get('user') %}
<h1>Success</h1>
  {% endif %}
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/register.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
<form method="post">
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Register">
</form>
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/update.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Edit "{{ post['summary'] }}"{% endblock %}</h1>
{% endblock %}



{% block content %}
<form method="post" style="display:flex; flex-direction:column">
    <label for="title">Title</label>
    <input name="title" id="title"
           value="{{ request.form['title'] or post['summary'] }}" required>
    <label for="date">Date</label>
    <input type="date" name="date" id="date"
           value="{{ request.form['date'] or date }}" required>
    <label for="start">Start</label>
    <input name="start" id="start"
           value="{{ request.form['start'] or start_time }}" required>
    <label for="end">End</label>
    <input name="end" id="end"
           value="{{ request.form['end'] or end_time }}" required>
    <label for="loc">Location</label>
    <textarea name="loc" id="loc">{{ request.form['loc'] or post['location'] }}</textarea>
    <input type="submit" value="Save">
</form>
<hr>
<form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
</form>
{% endblock %}